# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsideapp', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='affiliations',
            field=models.ManyToManyField(to='outsideapp.Affiliation'),
        ),
    ]
