# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', myapp.models.CustomModelField(max_length=255, validators=[myapp.models.dummy_validator_for_custom_field], verbose_name='Title')),
                ('lines', models.DecimalField(decimal_places=0, max_digits=10, validators=[myapp.models.dummy_validator_for_lines], verbose_name='Lines')),
            ],
        ),
    ]
